### ISSUE TITLE
SLN files saved in the wrong encoding

### ISSUE THREAD

**Issue by MaximRouiller** [endjin/Templify#15]
SLN files saved as ANSI can't be understood by VS2010 version selector. The result is that I can't open the solution from the file explorer but I can open it only from Visual Studio.

Opened the SLN file in Notepad++ and changed the encoding to UTF8 and it started working as expected again.

CSPROJ are not affected, CS files with special characters are not affected.

**Comment by HowardvanRooijen** [comment]
Fixed - force FileContentProcessor to write files as UTF8
