### ISSUE TITLE
Endjin.Templify.Client.ViewModel.ManageExclusionsViewModel.Save do not handle exceptions

### ISSUE THREAD

**Issue by MaximRouiller** [endjin/Templify#16]
Application crash with an unhandled exception when the file is not accessible for write operation.

Writing this file in Program Files require Administrator privileges when the UAC is enabled under Windows 7 32bits. 

Found some information on how to do it here:
http://www.aneef.net/2009/06/29/request-uac-elevation-for-net-application-managed-code/
http://en.wikipedia.org/wiki/User_Account_Control#Requesting_elevation

Another solution would be to save those information somewhere else where write rights are permitted for the current user.

**Comment by HowardvanRooijen** [comment]
I have moved the config file to:

\AppData\Roaming\Endjin\Templify\config\Templify.config

which means a non-admin user should be able to read / write without elevating privileges.
