### ISSUE TITLE
Directory/File exclusions does not support wildcards.

### ISSUE THREAD

**Issue by MaximRouiller** [endjin/Templify#17]
Using a \* in the folder name or a filename does not work. 

Default behavior should be what's present right now but we should definitely support wildcard in folders and files.

Some tools (namely ReSharper) generates folder in the solution folders and they could easily be forgotten by the user. However, these folders do not have a static name and they vary with the project name. A wildcard character for managing the exceptions would help solve this issue.

**Comment by HowardvanRooijen** [comment]
Added RegExp support for directory exclusions and also added resharper temp folders as a default exclusion.

You should not be able to specify "_ReSharper._" or ".su_" style exclusions.
