### ISSUE TITLE
Templify Here Slow

### ISSUE THREAD

**Issue by ronnieoverby** [endjin/Templify#23]
I templified a project. When I "Templify Here"'d the process was very slow and after 20 minutes, I just killed it.

**Comment by alecwhittington** [comment]
How large was the project you Templified? With the S# Templify package, it should take no longer than 5 mins. Can you provide more details that "the process was very slow"?

**Comment by ronnieoverby** [comment]
All I know is that it was not a big project (2 projects in solution) and it
was extremely slow ( 1 hour + ) last time I tried, before just killing the
process.

**Comment by HowardvanRooijen** [comment]
I think I've located a way to do much faster compression and extraction. I'll spike it and see if it makes any difference. Sorry for the delay - GitHub isn't sending me notifications of issues on this project.

**Comment by ronnieoverby** [comment]
Any update on this? I just fresh installed templify and templified the included sharp arch. project. It took 6 minutes. 6 MINUTES on a lightning fast machine is Windows 8 Pro RTM, 8 Cores @ 4.15ghz, 32gb of DDR3, with an extremely fast SSD.

What does this thing do that takes so long?

**Comment by HowardvanRooijen** [comment]
I believe it's the 7Zip api that takes the time, or should I say the call I have to make. VNext will more than likely be nuget compatible - so you'll see similar perf.

**Comment by ondesertverge** [comment]
This looks like such a great tool :+1: But, if it takes 2 hrs. to setup a package it just is unsuable like this. Is there a simple solution to this issue?

**Comment by HowardvanRooijen** [comment]
Solution is to replace the 7Zip implementation with a standard Zip implementation which should offer a faster package / unpackage speed.

**Comment by ondesertverge** [comment]
Howard hi,

Thanks a mil for the quick response. If you don't mind I'd like to discuss
just a bit ...

If I use 7Zip directly it takes only a few seconds to unzip. Is there
possibly something else I should be looking at?

And, possibly I should remove all Nuget packages so the binaries don't need
to be decompressed?

Thanks,
David

On Tue, Mar 5, 2013 at 5:29 PM, Howard van Rooijen <notifications@github.com

> wrote:
> 
> Solution is to replace the 7Zip implementation with a standard Zip
> implementation which should offer a faster package / unpackage speed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14445523
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
Hi,

as mentioned above - I think the problem is in the 7Zip API we use - to get access to specific files (to tokenise, or move into a location specified in the manifest file) - it seems to be quite slow. It's looking more like V2 will be nuget compatible - and will drop support for the manifest file / 7Zip so things should be super speedy. Only problem is my lack of time to make it happen :(

**Comment by ondesertverge** [comment]
So it looks like you unziping many times ... can you think of a quick fix
to unzip all at once and then do the work on the unzipped files.

Pls let me know if I am overstepping the line by taking too much of your
time ...

your help is much appreciated

On Tue, Mar 5, 2013 at 5:37 PM, Howard van Rooijen <notifications@github.com

> wrote:
> 
> Hi,
> 
> as mentioned above - I think the problem is in the 7Zip API we use - to
> get access to specific files (to tokenise, or move into a location
> specified in the manifest file) - it seems to be quite slow. It's looking
> more like V2 will be nuget compatible - and will drop support for the
> manifest file / 7Zip so things should be super speedy. Only problem is my
> lack of time to make it happen :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14446001
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
Not off the top of my head - the whole extraction piece needs to be rethought - I'd love to have time to do it, but I have 0 hobby coding time at the moment - I feel bad because it could really do with a couple of days of my time to get v2 spiked and working - then others could take it and run with it. A few people have asked if they can contribute - maybe I'll pass this quick fix by them?

**Comment by ondesertverge** [comment]
I'll pull the source and see if can get somthing working for my needs. If I
have any input I'll let you know. Thanks again

On Tue, Mar 5, 2013 at 5:46 PM, Howard van Rooijen <notifications@github.com

> wrote:
> 
> Not off the top of my head - the whole extraction piece needs to be
> rethought - I'd love to have time to do it, but I have 0 hobby coding time
> at the moment - I feel bad because it could really do with a couple of days
> of my time to get v2 spiked and working - then others could take it and run
> with it. A few people have asked if they can contribute - maybe I'll pass
> this quick fix by them?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14446561
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
That'll be great. Much appreciated.

**Comment by HowardvanRooijen** [comment]
SevenZipProcessor & SevenZipBuilder are the two bits you need to look at and replace with a ZipProcessor and ZipBuilder.

**Comment by HowardvanRooijen** [comment]
Hopefully the rest of the architecture is sufficiently abstracted that it'll "Just Work"(TM)

**Comment by ronnieoverby** [comment]
btw... why compress at all? Would archiving in storage mode (no compression) solve this problem? I, for one, have plenty of hard drive space.

**Comment by HowardvanRooijen** [comment]
It was more a distribution problem. The test case was always the Sharp Architecture Package - that didn't seem to take an excessively long time to process.

I'm open to all solutions - it's just time to implement them that's the problem!

**Comment by ondesertverge** [comment]
Well, thanks for the idea. I have begun trying to change the unzip loop in
'SevenZipProcessor' to single extract (much faster) and then copy the files
one by one, or maybe just unzip the whole bunch to directly to the
InstallPath.

I am not yet familiar with the inner workings and am playing around.

But if you say there is 'storage mode setting' when 'Templfying This' then
that would be the way to go. I'll have a look ...

On Tue, Mar 5, 2013 at 9:32 PM, Ronnie Overby notifications@github.comwrote:

> btw... why compress at all? Would archiving in storage mode (no
> compression) solve this problem? I, for one, have plenty of hard drive
> space.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14460108
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by ondesertverge** [comment]
and BTW, very nice code, easy to read and grasp, kudos! :)

On Tue, Mar 5, 2013 at 9:34 PM, Howard van Rooijen <notifications@github.com

> wrote:
> 
> It was more a distribution problem. The test case was always the Sharp
> Architecture Package - that didn't seem to take an excessively long time to
> process.
> 
> I'm open to all solutions - it's just time to implement them that's the
> problem!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14460214
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
In v2 I'd really like all these internal bits to be more pluggable and orderable - so you can insert your own plugin into what ever bit of the processing pipeline.

As for storage - you still need to add them to some kind of container as the delivery package - it just depends whether you need / want to compress it.

Thanks - I look at the code and grimace a little - it's the first and only time I've used MEF and have to say when V2 happens - MEF wont be part of it! The MVVM bits are nice, as it the TPL.

I refactored the code base severely - because in the 1st spike every time I didn't follow the SRP - it caused a bug / issue somewhere - so pretty much everything is SRP in there now - should make it easier to replace bits!

**Comment by HowardvanRooijen** [comment]
I'm not sure this is in the notes anywhere - but if you set the start up project to be Endjin.Templify.Client then open the properties pane and set the command line arguments to be (adjusting for your local path):

![templify-vs-options](https://f.cloud.github.com/assets/128664/224209/5762a7d4-85ce-11e2-8115-e9734518f903.png)

Makes debugging a lot easier.

**Comment by ondesertverge** [comment]
did and done thx, ;)
my problems is with grabbing the CommandOptions from within the Extraxtor,
any hints?

On Tue, Mar 5, 2013 at 9:53 PM, Howard van Rooijen <notifications@github.com

> wrote:
> 
> I'm not sure this is in the notes anywhere - but if you set the start up
> project to be Endjin.Templify.Client then open the properties pane and set
> the command line arguments to be (adjusting for your local path):
> 
> [image: templify-vs-options]https://f.cloud.github.com/assets/128664/224209/5762a7d4-85ce-11e2-8115-e9734518f903.png
> 
> Makes debugging a lot easier.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14461384
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
Only think I can think of is passing it down the stack. I was thinking about having a more generic processing context available - but you know what the story is there :(

**Comment by ondesertverge** [comment]
My thought is to put the Temp path next to the Install path in
ManifestFile, but I don't want to bore you with my trials, I'll let you
know if I come up with anything, you can then judge if there is any value
in my solution

On Tue, Mar 5, 2013 at 10:02 PM, Howard van Rooijen <
notifications@github.com> wrote:

> Only think I can think of is passing it down the stack. I was thinking
> about having a more generic processing context available - but you know
> what the story is there :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14461821
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by ondesertverge** [comment]
Okay -- so I managed to remove the need for the in-loop 7Zip work by
unzipping to the user's Temp folder and then copying from there file by
file using the InstallPath ...

Worked like a charm, cutting the running time from x hours to under two
minutes.

I guess the problem is a combination of having reference binaries in the
nuget folder and having 7Zip work in a loop (and maybe, as was suggested,
the use of compression period).

On Tue, Mar 5, 2013 at 10:56 PM, David Perlman david@aceff.co.il wrote:

> My thought is to put the Temp path next to the Install path in
> ManifestFile, but I don't want to bore you with my trials, I'll let you
> know if I come up with anything, you can then judge if there is any value
> in my solution
> 
> On Tue, Mar 5, 2013 at 10:02 PM, Howard van Rooijen <
> notifications@github.com> wrote:
> 
> > Only think I can think of is passing it down the stack. I was thinking
> > about having a more generic processing context available - but you know
> > what the story is there :(
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14461821
> > .
> 
> ## 
> 
> _David Perlman
> ACe__ff_ - Application and Control
> _c_ 052-4295495
> _f_ 153-52-6071812

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
Nice! Good work!

**Comment by HowardvanRooijen** [comment]
Have you kept the project as a VS2010 project (and there for can build the installer) or did you upgrade to VS2012? If you can produce an installer - I'll upload it for distribution. Also does it clean up after itself?

**Comment by ondesertverge** [comment]
:( 2012, so sorry.
1 -- No cleanup since it sits in system temp (is this wrong?)
2 -- I add no more than 10-20 lines of code, so I can rewrite them in 2010
3 -- I am not a real GitHub user, so what would be the best way to merge
these changes?

On Tue, Mar 5, 2013 at 11:35 PM, Howard van Rooijen <
notifications@github.com> wrote:

> Have you kept the project as a VS2010 project (and there for can build the
> installer) or did you upgrade to VS2012? If you can produce an installer -
> I'll upload it for distribution. Also does it clean up after itself?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14466797
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
No - don't worry - I've only got 2012 too! Was just hoping to save myself some work - but that's OK - I'll migrate it to an AdvancedInstaller template - that wont take two ticks.
1. ok - makes sense (I'll try and control my OCD)
3. If you've forked it - just push your changes and issue me a pull request.

**Comment by ondesertverge** [comment]
okay, got it forked and pushed up and sent out the pull request ...
on #2 above, may not be OCD after all :) ...
http://stackoverflow.com/questions/11173444/temporary-files-folders-on-windows...
looks like windows temp folders stay put until a disk clean-up is
initiated.

On Tue, Mar 5, 2013 at 11:42 PM, Howard van Rooijen <
notifications@github.com> wrote:

> No - don't worry - I've only got 2012 too! Was just hoping to save myself
> some work - but that's OK - I'll migrate it to an AdvancedInstaller
> template - that wont take two ticks.
> 2. ok - makes sense (I'll try and control my OCD)
> 3. If you've forked it - just push your changes and issue me a pull
> request.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14467198
> .

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by ondesertverge** [comment]
Howard hi,

After a good night's sleep I did some rethinking.

Why not unzip directly to the InstallFolder?

So I made this update and pushed the commit.

I also moved the unzip work to its own thread and rewired the progress bar
update.

Regards,
David

On Wed, Mar 6, 2013 at 12:26 AM, David Perlman david@aceff.co.il wrote:

> okay, got it forked and pushed up and sent out the pull request ...
> on #2 above, may not be OCD after all :) ...
> http://stackoverflow.com/questions/11173444/temporary-files-folders-on-windows... looks like windows temp folders stay put until a disk clean-up is
> initiated.
> 
> On Tue, Mar 5, 2013 at 11:42 PM, Howard van Rooijen <
> notifications@github.com> wrote:
> 
> > No - don't worry - I've only got 2012 too! Was just hoping to save myself
> > some work - but that's OK - I'll migrate it to an AdvancedInstaller
> > template - that wont take two ticks.
> > 2. ok - makes sense (I'll try and control my OCD)
> > 3. If you've forked it - just push your changes and issue me a pull
> > request.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/endjin/Templify/issues/23#issuecomment-14467198
> > .
> 
> ## 
> 
> _David Perlman
> ACe__ff_ - Application and Control
> _c_ 052-4295495
> _f_ 153-52-6071812

## 

_David Perlman
ACe__ff_ - Application and Control
_c_ 052-4295495
_f_ 153-52-6071812

**Comment by HowardvanRooijen** [comment]
Excellent. If I try and sprain my brain to remember - I think there may have been a reason for the 2 step unpacking process - some edge case that I caught during testing - but I can't remember what it was! I'll see if I can create the AdvancedInstaller on the train into work this morning - then we might have something we can push out.
And there was much rejoicing.

**Comment by HowardvanRooijen** [comment]
Hi,

Long overdue (been a bit busy here) but I’ve pulled in your changes and I’m just about to create a new installer so we can push out the improved version.

Thanks for your help.

/h

**Comment by HowardvanRooijen** [comment]
I've just pushed up a new release with the performance fix, a fix for file encoding error and a new installer https://dl.dropboxusercontent.com/u/5892928/Templify/Templify-Installer.exe
