### ISSUE TITLE
Toast notification error "object reference not set to an instance of an object”

### ISSUE THREAD

**Issue by dongol** [endjin/Templify#29]
I am getting an error "object reference not set to an instance of an object” when I try to templify the folder with right click and “templify this folder”. The error is displayed on the toast notification. If I tied to click on the “Templify” button with same name, i get the error “An item with the same key has already been added” but in real the template is not created at all. 
It was working fine for few days and suddenly start getting these error and I tried in different computer, got the same error.

**Comment by HowardvanRooijen** [comment]
Hi, thanks for posting the issue.
What OS are you running?

**Comment by dongol** [comment]
win 7 pro

**Comment by HowardvanRooijen** [comment]
Have you resolved the issue or did you accidentally close it?

**Comment by dongol** [comment]
it was an accident, all I remember was posting a comment. I didn't mean to close it, I think I might clicked on close instead of comment.

**Comment by dongol** [comment]
Howard, I tried in with fresh installation in Win 8 Pro, it worked perfectly fine. The only issue I'm having with my win 7 pro OS.

**Comment by HowardvanRooijen** [comment]
Hi,

Silly question - does it fail on all projects or just a particular one?
I'll try and stick some more logging in the app and do you a new build today.

**Comment by dongol** [comment]
its on all project

**Comment by dongol** [comment]
Hi Howard, 

I did clean installation again, it worked this time. Don't know why it didn't worked before. 

Thanks for you support and developing such a nice tool.
